import Header from "@/components/Header";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import "./globals.css";
import { Box } from "@mui/material";
import Copyright from "@/components/Copyright";
import Divider from "@mui/material/Divider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// export async function generateMetadata({ params }) {
//   console.log(params);
//   return {
//     title: "...",
//   };
// }
export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <ThemeRegistry>
          <Header />
          <Box component={"main"} sx={{ py: 10 }}>
            {children}
          </Box>
          <Divider />
          <Copyright />
        </ThemeRegistry>
      </body>
    </html>
  );
}
